### ISSUE TITLE
Dies ist ein Test Issue

### ISSUE THREAD

**Issue by Hannes-Bruns** [Vexxes/PenaltyCatalog#3]
Brauchen wir ein externes Tieckt System oder reicht uns das aus?

**Comment by Vexxes** [comment]
Ich glaube das reicht für uns schon aus. Hatte mir auch schon YouTrack angeschaut, aber das ist wahrscheinlich viel zu viel für so ne kleine Sache.
Alles was man braucht, kann man hier bestimmt auch machen. Ticket erstellen, jemanden zuweisen, bisschen kommentieren, fertig.

**Comment by Hannes-Bruns** [comment]
Perfekt
